### ISSUE TITLE
Generated Package.swift points to dev branch, missing a dependency

### ISSUE THREAD

**Issue by knvsl** [Azure/autorest.swift#310] opened 2021-03-15 17:53 UTC
Package.swift is generated inside Chat by autorest. It points to `dev/AzureCore` instead of `master` and missing dependency on `AzureCommunication`.

What's currently generated:

```
// swift-tools-version:5.1
//  The swift-tools-version declares the minimum version of Swift required to build this package.
//
// --------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// --------------------------------------------------------------------------

import PackageDescription

let package = Package(
    name: "AzureCommunicationChat",
    platforms: [
        .macOS(.v10_15), .iOS(.v12), .tvOS(.v12)
    ],
    products: [
        .library(name: "AzureCommunicationChat", type: .static, targets: ["AzureCommunicationChat"])
    ],
    dependencies: [
        .package(
            url: "https://github.com/Azure/azure-sdk-for-ios.git",
            .branch("dev/AzureCore")
        )
    ],
    targets: [
        // Build targets
        .target(
            name: "AzureCommunicationChat",
            dependencies: ["AzureCore"],
            path: "Source"
        )
    ],
    swiftLanguageVersions: [.v5]
)
```

**Comment by tjprescott** [comment] 2021-04-14 17:28
The generated Package.swift is only intended to be a starting template. You would then manually add any additional dependencies. The bug is that currently, Autorest.Swift always overwrites Package.swift, which it isn't intended to do. This behavior is fixed in #311.

**Comment by tjprescott** [comment] 2021-05-05 21:59
And the fact that autorest generates `Package.swift` to target `dev/AzureCore` is intentional for regenerating tests. For actual SDKs, you can change this to target whatever you want (presumably, a `from: "1.0.0"` type requirement.

**Comment by tjprescott** [comment] 2021-05-05 22:00
Now that #311 has been merged, the Package.swift file should not be overwritten by regeneration, so Autorest is behaving as intended. Closing this.

**Closed by tjprescott** 2021-05-05 22:00 UTC
